// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0_W_ZoG74IsBl7-pY65yh7F8AsqHeCA',
    appId: '1:706675456476:web:66b66a6df6c6e5aeb67719',
    messagingSenderId: '706675456476',
    projectId: 'miapp-fc288',
    authDomain: 'miapp-fc288.firebaseapp.com',
    storageBucket: 'miapp-fc288.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDddXkbEhPj8UfP-7PAscx8D0liTNGnBJ0',
    appId: '1:706675456476:android:705a7a18ec9e8c1cb67719',
    messagingSenderId: '706675456476',
    projectId: 'miapp-fc288',
    storageBucket: 'miapp-fc288.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGR6PF6lNXh7V2Mdwj1cg2z5B2VoTFNO8',
    appId: '1:706675456476:ios:763ee5198d648d67b67719',
    messagingSenderId: '706675456476',
    projectId: 'miapp-fc288',
    storageBucket: 'miapp-fc288.appspot.com',
    iosBundleId: 'com.example.miapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGR6PF6lNXh7V2Mdwj1cg2z5B2VoTFNO8',
    appId: '1:706675456476:ios:763ee5198d648d67b67719',
    messagingSenderId: '706675456476',
    projectId: 'miapp-fc288',
    storageBucket: 'miapp-fc288.appspot.com',
    iosBundleId: 'com.example.miapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV0_W_ZoG74IsBl7-pY65yh7F8AsqHeCA',
    appId: '1:706675456476:web:4a5b7b7d0c47676fb67719',
    messagingSenderId: '706675456476',
    projectId: 'miapp-fc288',
    authDomain: 'miapp-fc288.firebaseapp.com',
    storageBucket: 'miapp-fc288.appspot.com',
  );
}
